extends: airbnb-base
env:
  es6: true
  node: true
  mocha: true
parserOptions:
  ecmaVersion: 6
  sourceType: script
plugins: [ mocha ]
rules:
  comma-dangle: off
  max-len: [ warn, 140]
  object-shorthand: off
  no-console: warn
  complexity: [ warn, 6]
  class-methods-use-this: [0]
  no-underscore-dangle: off
  mocha/no-exclusive-tests: error
  import/no-dynamic-require: warn